### ISSUE TITLE
２種類の幅に１つのソースで対応できるようにする。

### ISSUE THREAD

**Issue by tejima** [kashiwasan/opTimelinePlugin#31]
opSkinBasicPluginは幅が狭い

opSkinUnitedPluginは幅が広い（OpenPNE3.8以降の標準レイアウト）

CSS使わないでできる？
幅指定だけ使うというのもあり。

**Comment by upsilon** [comment]
b4542095dbe5864df6dfd6c1992d6b84da332c0f にて、.timeline-post-comment-form-input 以外の要素については opSkinUnitedPlugin での幅広表示に対応しました。
