### ISSUE TITLE
コミュニティタイムラインで文字数カウントが表示されない

### ISSUE THREAD

**Issue by upsilon** [kashiwasan/opTimelinePlugin#42]
https://redmine.openpne.jp/issues/3151 より転記。
### Overview (現象)

コミュニティタイムラインで文字数カウントが表示されない
コミュニティタイムラインにおいても文字数のカウントがされるよう修正されるべき
### Environment (再現バージョン)

opTimelinePlugin 0.9.2
### Way to repro (再現手順)
1. 管理画面ホーム画面ガジェット設定ページ(/pc_backend.php/design/gadget/type/gadget)でタイムラインガジェットを追加する
2. SNSにログインし参加しているコミュニティページ(/community/xxxx)にアクセスする
3. コミュニティタイムラインの入力フォームで入力しても文字数のカウントが表示されない

**Comment by ichikawatatsuya** [comment]
counter.jsを呼び出す
