### ISSUE TITLE
スマホ版タイムラインに投稿時間が表示されない

### ISSUE THREAD

**Issue by upsilon** [kashiwasan/opTimelinePlugin#43]
https://redmine.openpne.jp/issues/3002 より転記。
### Environment (再現バージョン)

OpenPNE3.8RC1
### Way to repro (再現手順)
1. 管理画面でホーム画面にタイムラインガジェットを追加しておく
2. ホーム画面(memberer/home)でタイムラインに投稿する
3. 手順1 で投稿したタイムラインに投稿時間が表示されるか確認する

![3.8RC1_1334825041444.jpeg](https://redmine.openpne.jp/attachments/download/431)
### Way to fix (修正内容)

スマホ版タイムラインに投稿時間が表示されるように修正お願いします。

**Comment by ichikawatatsuya** [comment]
PC版JSにある投稿時間を表示する関数をスマホ版に持ってくる
