### ISSUE TITLE
新規登録時にスクリーンネームを日本語で登録できてしまう

### ISSUE THREAD

**Issue by upsilon** [kashiwasan/opTimelinePlugin#47]
https://redmine.openpne.jp/issues/3054 より転記。
### 概要

新規登録時にスクリーンネームを日本語で登録できてしまう．

設定変更画面（ /member/config?category=timelineScreenName ) では英数字のみとなっているが，新規登録時には日本語が登録できてしまう．

**Comment by tejima** [comment]
スクリーンネームはOpenPNE本体で実装するまでは作らないので、Timelineからは外します。
